const actions = {
    GET_CHARACTERS_LIST_STARTED: "GET_CHARACTERS_LIST_STARTED",
    GET_CHARACTERS_LIST_SUCCESS: "GET_CHARACTERS_LIST_SUCCESS",
    GET_CHARACTERS_LIST_FAILURE: "GET_CHARACTERS_LIST_FAILURE",

    GET_CHARACTER_INFO_STARTED: "GET_CHARACTER_INFO_STARTED",
    GET_CHARACTER_INFO_SUCCESS: "GET_CHARACTER_INFO_SUCCESS",
    GET_CHARACTER_INFO_FAILURE: "GET_CHARACTER_INFO_FAILURE",
};

export default actions;